# Generated by Django 3.1.3 on 2020-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnMatchedFan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sid', models.IntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_yh', models.CharField(max_length=100)),
                ('url_yh', models.URLField(blank=True, null=True)),
                ('sid', models.IntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('cover_loc', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_episodes', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('matched', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='main.Tag')),
            ],
        ),
    ]
